# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d566f7a99f8060ffa6887a89510cc0af0841cddd01642d3f007911ad14073587ae75cfb252cc47539f7685e52ceba486d425a8e7d738c7dc52b00a9fa9d2e2

test:
  secret_key_base: 3ef498f1858cb447db717c50924c24b8e4a944b2412f49f1c71ebcf149b4327148a6943546d7f4a65ea96944fae108d5cb85e95672fa56dbbfc1aa55567072c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
